config/routes.rb
Rails.application.routes.draw do


   devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about",as: "about"
    get "customers/my_page" => "customers#show",as: "customer"
    get "customers/registration_edit" => "customers#edit",as: "edit_customer"
    patch "customers/registration_edit" => "customers#update",as: "customers"
    get "customers/confirm" => "customers#confirm",as: "confirm"
    patch "customer/secession" => "customers#secession",as: "secession"
    resources :addresses,except:[:new, :show, :destroy]
    delete "addresses/:id" => "addresses#destroy",as: "destroy_address"
    resources :items,only:[:index, :show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all",as: "destroy_all"
    resources :cart_items, only:[:index, :create, :update, :destroy]
    get "orders/thanks" => "orders#thanks",as: "thanks"
    resources :orders, only:[:new, :index, :show]
    post "orders/confirm" => "orders#confirm",as: "order_confirm"
    post "orders" => "orders#create",as: "create_orders"
  end


  namespace :admin do
    root to: "homes#top"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, except:[:destroy]
    resources :customers ,only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-6">
      <label class="mt-4 mb-4 lead bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</label>

      <%= form_with model: @customer,url: admin_customer_path do |f| %>
      <div class="form-group">
        <label>会員ID</label>
        <%= f.text_field :id %>
      </div>
      <div class="form-group">
        <label>氏名</label>
        <%= f.text_field:last_name %> <%= f.text_field:first_name %>
      </div>
      <div class="form-group">
        <label>フリガナ</label>
        <%= f.text_field:last_name_kana %> <%= f.text_field:first_name_kana %>
      </div>
      <div class="form-group">
        <label>郵便番号</label>
        <%= f.text_field :postal_code %>
      </div>
      <div class="form-group">
        <label>住所</label>
        <%= f.text_field :address %>
      </div>
      <div class="form-group">
        <label>電話番号</label>
        <%= f.text_field :address %>
      </div>
      <div class="form-group">
        <label>メールアドレス</label>
        <%= f.text_field :email %>
      </div>
      <div class="form-group">
        <label>会員ステータス</label>
        <%= f.radio_button :is_active, "false",checked: true %>有効 <%= f.radio_button :is_active, "ture"  %>退会
      </div>
      <%= f.submit "変更を保存",class: "btn btn-success" %>
      <% end %>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <label class="mt-4 mb-4 lead bg-light">会員一覧</label>
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @customers.each do |customer| %>
    <tbody>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_active == true %>
            退会
          <% else %>
            <label class="text-success">有効</label>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <label class="mt-4 mb-4 lead bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</label>
      <div>
        <label>会員ID</label>
        <%= @customer.id %>
      </div>
      <div>
        <label>氏名</label>
        <%= @customer.last_name %> <%= @customer.first_name %>
      </div>
      <div>
        <label>フリガナ</label>
        <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
      </div>
      <div>
        <label>郵便番号</label>
        <%= @customer.postal_code %>
      </div>
      <div>
        <label>住所</label>
        <%= @customer.address %>
      </div>
      <div>
        <label>電話番号</label>
        <%= @customer.telephone_number %>
      </div>
      <div>
        <label>メールアドレス</label>
        <%= @customer.email %>
      </div>
      <div>
        <label>会員ステータス</label>
        <% if @customer.is_active == true %>
          退会
        <% else %>
          <label class="text-success">有効</label>
        <% end %>
      </div>
      <div class="mt-3">
        <%= link_to edit_admin_customer_path(@customer) do %>
          <label class="btn btn-success mr-5">編集する</label>
        <% end %>
        <%= link_to admin_root_path do %>
          <label class="btn btn-primary ml-5">注文履歴一覧を見る</label>
        <% end %>
      </div>
    </div>
  </div>
</div>