config/routes.rb
Rails.application.routes.draw do


   devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about",as: "about"
    get "customers/my_page" => "customers#show",as: "customer"
    get "customers/registration_edit" => "customers#edit",as: "edit_customer"
    patch "customers/registration_edit" => "customers#update",as: "customers"
    get "customers/confirm" => "customers#confirm",as: "confirm"
    patch "customer/secession" => "customers#secession",as: "secession"
    resources :addresses,except:[:new, :show, :destroy]
    delete "addresses/:id" => "addresses#destroy",as: "destroy_address"
    resources :items,only:[:index, :show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all",as: "destroy_all"
    resources :cart_items, only:[:index, :create, :update, :destroy]
    get "orders/thanks" => "orders#thanks",as: "thanks"
    resources :orders, only:[:new, :index, :show]
    post "orders/confirm" => "orders#confirm",as: "order_confirm"
    post "orders" => "orders#create",as: "create_orders"
  end


  namespace :admin do
    root to: "homes#top"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, except:[:destroy]
    resources :customers ,only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_item, dependent: :destroy

  validates :profile_image, presence: true
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

  def add_tax_price
  (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  validates :ship_postal_code, presence: true
  validates :ship_postal_address, presence: true
  validates :ship_name, presence: true
  validates :request_money, presence: true
  validates :payment, presence: true

  enum payment: {credit_card: 0, transfer: 1 }

  enum status:{waiting: 0, confirm: 1, making: 2, preparation: 3, shipping: 4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  def subtotal
    purchase_price*amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
       redirect_to admin_genres_path
    else
      @genres = Genre.all
      @genre = Genre.new
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
       redirect_to admin_item_path(@item)
    else
      @item = Item.new
      @genres = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:profile_image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = @order_details.inject(0){|sum, order_detail| sum + order_detail.subtotal}
    @order.postage = 800
    @customer = @order.customer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="navbar-brand p-3" >
            <%= link_to root_path do %>
            <%= image_tag('logo.png') %>
            <% end %>
          </div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_items_path ,class: "btn btn-default" do %>
                  商品一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_customers_path ,class: "btn btn-default" do %>
                  会員一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_root_path ,class: "btn btn-default" do %>
                  注文履歴一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path ,class: "btn btn-default" do %>
                  ジャンル一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete ,class: "btn btn-default" do %>
                  ログアウト
                <% end %>
              </li>
            <% elsif customer_signed_in? %>
               <li class="nav-item">
                <%= link_to customer_path ,class: "btn btn-default" do %>
                  マイページ
                <% end %>
              </li>
               <li class="nav-item">
                <%= link_to items_path ,class: "btn btn-default" do %>
                  商品一覧
                <% end %>
              </li>
               <li class="nav-item">
                <%= link_to cart_items_path ,class: "btn btn-default" do %>
                  カート
                <% end %>
              </li>
               <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete ,class: "btn btn-default" do %>
                  ログアウト
                <% end %>
              </li>
            <% else %>
             <li class="nav-item">
                <%= link_to about_path,class: "btn btn-default" do %>
                  About
                <% end %>
              </li>
             <li class="nav-item">
                <%= link_to items_path ,class: "btn btn-default" do %>
                  商品一覧
                <% end %>
              </li>
             <li class="nav-item">
                <%= link_to new_customer_registration_path ,class: "btn btn-default" do %>
                  新規登録
                <% end %>
              </li>
             <li class="nav-item">
                <%= link_to new_customer_session_path ,class: "btn btn-default" do %>
                  ログイン
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>